table Date

	column Date
		dataType: dateTime
		sourceColumn: Date

	column Year
		dataType: int64
		sourceColumn: Year

	column Month
		dataType: int64
		sourceColumn: Month

	column MonthName
		dataType: string
		sourceColumn: MonthName

	column Quarter
		dataType: int64
		sourceColumn: Quarter

	column Day
		dataType: int64
		sourceColumn: Day

	column YearMonth
		dataType: string
		sourceColumn: YearMonth

	partition Date = m
		mode: import
		source =
				let
				    StartDate = #date(2021, 1, 1),
				    EndDate = #date(2024, 12, 31),
				    NumberOfDays = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, NumberOfDays, #duration(1, 0, 0, 0)),
				    DateTable = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    ChangedType = Table.TransformColumnTypes(DateTable,{{"Date", type date}}),
				    AddYear = Table.AddColumn(ChangedType, "Year", each Date.Year([Date]), Int64.Type),
				    AddMonth = Table.AddColumn(AddYear, "Month", each Date.Month([Date]), Int64.Type),
				    AddMonthName = Table.AddColumn(AddMonth, "MonthName", each Date.MonthName([Date]), type text),
				    AddQuarter = Table.AddColumn(AddMonthName, "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
				    AddDay = Table.AddColumn(AddQuarter, "Day", each Date.Day([Date]), Int64.Type),
				    AddYearMonth = Table.AddColumn(AddDay, "YearMonth", each Date.ToText([Date], "yyyy-MM"), type text)
				in
				    AddYearMonth

