table Geography

	column zip
		dataType: string
		sourceColumn: zip

	column lat
		dataType: double
		sourceColumn: lat

	column lng
		dataType: double
		sourceColumn: lng

	column city
		dataType: string
		sourceColumn: city

	column state_id
		dataType: string
		sourceColumn: state_id

	column state_name
		dataType: string
		sourceColumn: state_name

	column population
		dataType: int64
		sourceColumn: population

	column density
		dataType: double
		sourceColumn: density

	column county_name
		dataType: string
		sourceColumn: county_name

	column timezone
		dataType: string
		sourceColumn: timezone

	partition Geography = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\\Users\\benit\\Desktop\\PBI_MCP_DEMO\\DataSource\\uszips.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    SelectedColumns = Table.SelectColumns(PromotedHeaders,{"zip", "lat", "lng", "city", "state_id", "state_name", "population", "density", "county_name", "timezone"}),
				    ChangedType = Table.TransformColumnTypes(SelectedColumns,{{"zip", type text}, {"lat", type number}, {"lng", type number}, {"city", type text}, {"state_id", type text}, {"state_name", type text}, {"population", Int64.Type}, {"density", type number}, {"county_name", type text}, {"timezone", type text}})
				in
				    ChangedType

